autoops/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

autoops/asset/urls.py
from django.urls  import path
from . import api
from  .import views

urlpatterns = [
    path('asset.html',views.AssetListAll.as_view(),name='asset_list'),
    path('asset-add.html',views.AssetAdd.as_view(),name='asset_add'),
    path('asset-del.html',views.AssetDel.as_view(),name='asset_del'),
    path('asset-all-del.html',views.AssetAllDel.as_view(),name='asset_all_del'),
    path('asset-detail-<int:pk>.html',views.AssetDetail.as_view(),name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),




    path('asset-hardware-update.html', views.asset_hardware_update, name='asset_hardware_update'),
    path('asset-performance-<int:nid>.html', views.asset_performance, name='asset_performance'),
    path('asset-webssh.html', views.asset_web_ssh, name='asset_web_ssh'),

    path('system-user.html', views.SystemUserListAll.as_view(), name='system_user'),
    path('system-user-asset-<int:nid>.html', views.system_user_asset, name='system_user_asset'),
    path('system-user-add.html', views.system_user_add, name='system_user_add'),

    path('system-user-del.html', views.SystemUserDelete.as_view(), name='system_user_del'),


    path('system-user-detail-<int:nid>.html', views.system_user_detail, name='system_user_detail'),
    path('system-user-update-<int:nid>.html', views.system_user_update, name='system_user_update'),

    path('api/asset.html',api.AssetList.as_view(),name='asset_api_list'),
    path('api/asset-detail-<int:pk>.html', api.AssetDetail.as_view(), name='asset_api_detail'),

    path('asset-export.html',views.export,name='asset_export'),
]


app_name="asset"

autoops/autoops/urls.py
from django.conf.urls import include,url
from django.contrib import admin

from names.views import index,login_view,logout
from django.conf.urls import handler404, handler500
from asset.views import  AssetUpload
from django.conf import settings
from django.urls  import path

import xadmin
xadmin.autodiscover()

from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    path('admin/', xadmin.site.urls, name="xadmin"),
    path('dadmin/', admin.site.urls,name="dadmin"),
    path('', index),
    path('login.html', login_view,name="login_view"),
    path('logout.html', logout,name="logout"),
    path('index.html', index),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    path('db/', include('db.urls', namespace="db", ), ),
    path('tasks/', include('tasks.urls', namespace="tasks",), ),
    path('names/', include('names.urls', namespace="names",), ),
    path('library/', include('library.urls', namespace="library",), ),
    path('upload/',  AssetUpload.as_view()),
    path('ueditor/',include('DjangoUeditor.urls' )),
    path('release/', include('release.urls', namespace="release")),
]



if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoops/db/urls.py
from django.urls  import path
from  .import views

urlpatterns = [
    path('db.html',views.DbListAll.as_view(),name='db_list'),
    path('db-add.html',views.DbAdd.as_view(),name='db_add'),
    path('db-del.html',views.DbDel.as_view(),name='db_del'),
    path('db-all-del.html',views.db_all_del,name='db_all_del'),
    path('db-update-<int:pk>.html', views.DbUpdate.as_view(), name='db_update'),
    path('asset-detail-<int:pk>.html',views.DbDetail.as_view(),name='db_detail'),




    path('db-user.html', views.DbUserListAll.as_view(), name='db_user_list'),
    path('db-user-add.html', views.DbUserAdd.as_view(), name='db_user_add'),
    path('db-user-update-<int:pk>.html', views.DbUserUpdate.as_view(), name='db_user_update'),
    path('db-user-del.html', views.DbUserDel.as_view(), name='db_del'),
    path('db-user-detail-<int:pk>.html', views.DbUserDetail.as_view(), name='db_user_detail'),
    path('db-user-db-<int:nid>.html', views.Db_user_db, name='db_user_db'),
]


app_name="db"

autoops/asset/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from asset.models import asset, system_users, performance, web_history, data_centers
from .form import AssetForm, SystemUserForm
from names.password_crypt import encrypt_p, decrypt_p, pyecharts_add
from django.contrib.auth.models import User, Group
from guardian.shortcuts import assign_perm, get_perms
from guardian.core import ObjectPermissionChecker
from guardian.decorators import permission_required_or_403
from guardian.shortcuts import get_objects_for_user, get_objects_for_group
from django.contrib.auth.models import Permission
from guardian.models import UserObjectPermission, GroupObjectPermission
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy
from tasks.views import ssh
from autoops import settings
from django.db.models import Q
import xlwt, time, json
from django.template import loader
from pyecharts import Gauge, Line
import threading, time, datetime


from   tasks.ansible_2420.runner import AdHocRunner, CommandRunner
from  tasks.ansible_2420.inventory import BaseInventory



class AssetListAll(TemplateView):
    template_name = 'asset/asset.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AssetListAll, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
            "Webssh": getattr(settings, 'Webssh_ip'),
            "Webssh_port": getattr(settings, 'Webssh_port'),
            'asset_list': get_objects_for_user(self.request.user, 'asset.read_asset')
        }
        kwargs.update(context)
        return super(AssetListAll, self).get_context_data(**kwargs)

    def post(self, request):
        query = request.POST.get("name")

        user = User.objects.get(username=request.user)
        if user.is_superuser == 1:
            ret = asset.objects.filter(Q(network_ip=query) | Q(manage_ip=query) | Q(hostname=query) | Q(
                inner_ip=query) | Q(model=query) | Q(
                eth0=query) | Q(eth1=query) | Q(eth2=query) | Q(eth3=query) |
                                       Q(system=query) | Q(system_user__username=query) | Q(
                data_center__data_center_list=query) | Q(
                cabinet=query) |
                                       Q(position=query) | Q(sn=query)
                                       | Q(uplink_port=query) | Q(product_line__name=query)
                                       )
        else:
            product1 = Group.objects.get(user=user)

            ret = asset.objects.filter(Q(product_line__name=product1) &  Q(network_ip=query) | Q(manage_ip=query) | Q(hostname=query) | Q( inner_ip=query) | Q(model=query) | Q(eth0=query) | Q(eth1=query) | Q(eth2=query) | Q(eth3=query) |
                                       Q(system=query) | Q(system_user__username=query)
                                       | Q(data_center__data_center_list=query) | Q(cabinet=query) | Q(position=query) | Q(sn=query)| Q(uplink_port=query))

        return render(request, 'asset/asset.html',
                      {"Webssh": getattr(settings, 'Webssh_ip'),
                       "Webssh_port": getattr(settings, 'Webssh_port'),
                       "asset_active": "active",
                       "asset_list_active": "active", "asset_list": ret})




class AssetAdd(CreateView):
    model = asset
    form_class = AssetForm
    template_name = 'asset/asset-add.html'
    success_url = reverse_lazy('asset:asset_list')

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('asset.add_asset'))
    def dispatch(self, *args, **kwargs):
        return super(AssetAdd, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.asset_save = asset_save = form.save()

        myproduct = form.cleaned_data['product_line']
        mygroup = Group.objects.get(name=myproduct)

        GroupObjectPermission.objects.assign_perm("read_asset", mygroup, obj=asset_save)
        GroupObjectPermission.objects.assign_perm("add_asset", mygroup, obj=asset_save, )
        GroupObjectPermission.objects.assign_perm("change_asset", mygroup, obj=asset_save)
        GroupObjectPermission.objects.assign_perm("delete_asset", mygroup, obj=asset_save)
        GroupObjectPermission.objects.assign_perm("task_asset", mygroup, obj=asset_save)
        return super(AssetAdd, self).form_valid(form)

    def get_success_url(self):
        return super(AssetAdd, self).get_success_url()

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }
        kwargs.update(context)
        return super(AssetAdd, self).get_context_data(**kwargs)


class AssetUpdate(UpdateView):
    model = asset
    form_class = AssetForm
    template_name = 'asset/asset-update.html'
    success_url = reverse_lazy('asset:asset_list')

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('asset.add_asset', (asset, 'id', 'pk')))
    def dispatch(self, *args, **kwargs):
        return super(AssetUpdate, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "asset_active": "active",
            "asset_list_active": "active",
        }
        kwargs.update(context)
        return super(AssetUpdate, self).get_context_data(**kwargs)

    def form_invalid(self, form):
        print(form.errors)
        return super(AssetUpdate, self).form_invalid(form)

    def form_valid(self, form):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        old_myproduct = asset.objects.get(id=pk).product_line
        old_mygroup = Group.objects.get(name=old_myproduct)
        new_mygroup = Group.objects.get(name=form.cleaned_data['product_line'])

        self.object = form.save()
        if old_mygroup != new_mygroup:
            GroupObjectPermission.objects.remove_perm("read_asset", old_mygroup, obj=self.object)
            GroupObjectPermission.objects.remove_perm("add_asset", old_mygroup, obj=self.object)
            GroupObjectPermission.objects.remove_perm("change_asset", old_mygroup, obj=self.object)
            GroupObjectPermission.objects.remove_perm("delete_asset", old_mygroup, obj=self.object)
            GroupObjectPermission.objects.remove_perm("task_asset", old_mygroup, obj=self.object)

            GroupObjectPermission.objects.assign_perm("read_asset", new_mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("add_asset", new_mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("change_asset", new_mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("delete_asset", new_mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("task_asset", new_mygroup, obj=self.object)
        return super(AssetUpdate, self).form_valid(form)

    def get_success_url(self):
        return super(AssetUpdate, self).get_success_url()



class AssetDetail(DetailView):
    model = asset
    template_name = 'asset/asset-detail.html'

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('asset.read_asset', (asset, 'id', 'pk')))
    def dispatch(self, *args, **kwargs):
        return super(AssetDetail, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        detail = asset.objects.get(id=pk)

        context = {
            "asset_active": "active",
            "asset_list_active": "active",
            "assets": detail,
            "nid": pk,
        }
        kwargs.update(context)
        return super(AssetDetail, self).get_context_data(**kwargs)



class AssetDel(View):
    model = asset

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AssetDel, self).dispatch(*args, **kwargs)

    def post(self, request):
        ret = {'status': True, 'error': None, }
        try:
            id = request.POST.get('nid', None)
            print(id)
            users= User.objects.get(username=request.user)
            print(users)
            checker = ObjectPermissionChecker(users)
            assets = asset.objects.get(id=id)
            print(assets)

            if checker.has_perm('delete_asset', assets, ) == True:
                assets.delete()
        except Exception as e:
            ret = {
                "static": False,
                "error": '删除请求错误,没有权限{}'.format(e)
            }
        finally:
            return HttpResponse(json.dumps(ret))




class AssetAllDel(View):
    model = asset

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(AssetAllDel, self).dispatch(*args, **kwargs)

    def post(self, request):
        ret = {'status': True, 'error': None, }
        try:
            ids = request.POST.getlist('id', None)
            ids1 = []
            for i in ids:
                user = User.objects.get(username=request.user)
                checker = ObjectPermissionChecker(user)
                assets = asset.objects.get(id=i)
                if checker.has_perm('delete_asset', assets, ) == True:
                    ids1.append(i)

            idstring = ','.join(ids1)
            asset.objects.extra(where=['id IN (' + idstring + ')']).delete()

        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,没有权限{}'.format(e)
        finally:
            return HttpResponse(json.dumps(ret))



@login_required(login_url="/login.html")
def asset_hardware_update(request):

autoops/templates/asset/asset.html
{% extends "base.html" %}
{% load  mytags %}
{% load   guardian_tags %}


{% block header-css %}
<link href="/static/webssh_static/css/xterm.min.css" rel="stylesheet" type="text/css"/>
<link href="/static/webssh_static/css/fullscreen.min.css" rel="stylesheet" type="text/css"/>
{% endblock %}


{% block  title %}资产信息{% endblock %}







{% block page-content %}
<div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>资产信息</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>资产管理</a>
                </li>
                <li class="active">
                    <strong>资产信息</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>资产信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">


                            <form id="cha" class="form-horizontal" action="{% url 'asset:asset_list' %}" method="post">
                                {% csrf_token %}
                                <div class="col-md-2"><input type="text" class="form-control" name="name" required>
                                </div>

                                <button class="btn btn-primary" type="submit">查询</button>


                                <a href="{% url    'asset:asset_add' %}" class="btn btn-primary  ">
                                    添加</a>


                                <a class="btn btn-danger  asset_all_del"
                                >批量删除
                                </a>
                                <a href="{% url    'asset:asset_export' %}" class="btn btn-primary  ">
                                    导出全部</a>
                            </form>


                            <form id="del_form_asset_all" class="form-horizontal  ">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>外网IP</th>
                                        <th>管理IP</th>
                                        <th>产品线</th>
                                        <th>位置</th>
                                        <th>型号</th>
                                        <th>SN</th>
                                        <th>动作{{ error_performance }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   asset_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center"><a
                                                    href="{% url  "asset:asset_detail"   pk=row.id %}">{{ row.network_ip }}</a>
                                            </td>
                                            <td class="center">{{ row.manage_ip }}</td>
                                            <td class="center">{{ row.product_line.name }}</td>
                                            <td class="center">{{ row.cabinet }} {{ row.position }}</td>
                                            <td class="center">{{ row.model }}</td>
                                            <td class="center">{{ row.sn }}</td>
                                            <td><a class="btn btn-primary  btn-xs "
                                                   href="{%   url  "asset:asset_update"  pk=row.id %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  asset_del_1" data-toggle="modal"
                                                   data-target="#myModal1">删除
                                                </a>
                                                <a class="btn btn-primary  btn-xs "
                                                   href="{% url    "asset:asset_performance"   row.id %}">性能</a>
                                                <a type="button" class="btn btn-primary btn-xs webssh" >终端
                                                </a>


                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>
                            </form>


                        </div>

                    </div>


                </div>
            </div>
        </div>
    </div>



{% block footer-js %}

<script src="/static/webssh_static/js/xterm.min.js"></script>
<script src="/static/webssh_static/js/fullscreen.min.js"></script>


<script>
     $(function () {

       $(document).on('click','.asset_del_1',function () {

              $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
                    var id = $(this).parent().parent().attr('id');

                    swal({
                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {

                        $.ajax({
                            url: "/asset/asset-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });

                });

  $(document).on('click','.asset_all_del',function () {

                   $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});

                    swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                            url: "/asset/asset-all-del.html",
                            type: 'POST',
                            data: $('#del_form_asset_all').serialize(),
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });


            });


            jQuery(function ($) {


             $(document).on('click','.webssh',function (event) {


                    event.preventDefault();

                    var id_a = $(this).parent().parent().attr('id');

                    $.ajax({
                        headers: {"X-CSRFToken": '{{ csrf_token }}'},
                        url: "/asset/asset-webssh.html",
                        type: 'POST',
                        data: {'id': id_a},
                        success: function (ret) {

                            var obj = JSON.parse(ret);
                            var ips = obj.ip;
                            var ports = obj.port;
                            var usernames = obj.username;
                            var passwords = obj.password;

                            $.ajax({
                                url: "http://{{ Webssh }}:{{ Webssh_port }}/",
                                type: 'POST',
                                data: {hostname: ips, port: ports, username: usernames, password: passwords},
                                crossDomain: true,
                                success: callback
                            });

                                function current_geometry() {
                                    cols = parseInt(window.innerWidth / 10);
                                    rows = parseInt(window.innerHeight / 24);
                                    return [cols, rows];
                                  }



                            function callback(msg) {
                                console.log(msg);
                                if (msg.status) {
                                      swal("错误", "登陆" + "[ " + msg.status + " ]" + "遇到错误", "error");
                                      return;
                                }





                                var    url = "ws://{{ Webssh }}:{{ Webssh_port }}/" + 'ws?id=' + msg.id,
                                    socket = new WebSocket(url),
                                    terminal = document.getElementById('#terminal'),
                                    geometry = current_geometry();
                                    term = new Terminal({cursorBlink: true,  cols: geometry[0], rows: geometry[1]});

                                console.log(url);
                                term.on('data', function (data) {
                                    // console.log(data);
                                    socket.send(data);
                                });

                                socket.onopen = function (e) {
                                    $('.container1').hide();
                                    term.open(terminal, true);
                                    term.toggleFullscreen(true);
                                };

                                socket.onmessage = function (msg) {
                                    console.log(msg);
                                    term.write(msg.data);
                                };

                                socket.onerror = function (e) {
                                    console.log(e);
                                };

                                socket.onclose = function (e) {
                                    console.log(e);
                                    term.destroy();
                                    $('.container1').show();
                                    // status.text(e.reason);
                                };
                            }


                                            $(window).resize(function(){
                    if (typeof term != "undefined") {
                       geometry = current_geometry();
                       term.geometry = geometry;
                       term.resize(geometry[0], geometry[1]);
                     }
                   });

                        }
                    });
                });
            });

        </script>


    {% endblock %}

{% endblock %}

autoops/templates/asset/system-user-add.html
{% extends "base.html" %}
{% block  title %}系统用户添加{% endblock %}
{% block header-css %}

{% load	bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>系统用户添加</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="/asset/system-user.html">用户管理</a>
                </li>
                <li class="active">
                    <strong>系统用户添加</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h5>系统用户添加</h5>   <div style="color:red;" >  {{msg }}</div>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" action="{% url "asset:system_user_add" %}" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本</h3>


                                {% bootstrap_field form.name layout="horizontal" %}
                                {% bootstrap_field form.username layout="horizontal" %}
                                {% bootstrap_field form.password layout="horizontal" %}
                                {% bootstrap_field form.product_line layout="horizontal" %}
                                {% bootstrap_field form.ps layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>



                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                <button class="btn btn-primary" type="submit">保存</button>
                                <button class="btn btn-white" type="reset">重置</button>
                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>

    </div>


{% block footer-js %}
<script>
  function add_tr(obj) {
    var tr = $(obj).parent();
    tr.after(tr.clone());
  }

   function del_tr(obj) {
    $(obj).parent().remove();
  }
</script>

{% endblock %}



{% endblock %}