autoops/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

autoops/asset/urls.py
from django.urls  import path
from . import api
from  .import views

urlpatterns = [
    path('asset.html',views.AssetListAll.as_view(),name='asset_list'),
    path('asset-add.html',views.AssetAdd.as_view(),name='asset_add'),
    path('asset-del.html',views.AssetDel.as_view(),name='asset_del'),
    path('asset-all-del.html',views.AssetAllDel.as_view(),name='asset_all_del'),
    path('asset-detail-<int:pk>.html',views.AssetDetail.as_view(),name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),




    path('asset-hardware-update.html', views.asset_hardware_update, name='asset_hardware_update'),
    path('asset-performance-<int:nid>.html', views.asset_performance, name='asset_performance'),
    path('asset-webssh.html', views.asset_web_ssh, name='asset_web_ssh'),

    path('system-user.html', views.SystemUserListAll.as_view(), name='system_user'),
    path('system-user-asset-<int:nid>.html', views.system_user_asset, name='system_user_asset'),
    path('system-user-add.html', views.system_user_add, name='system_user_add'),

    path('system-user-del.html', views.SystemUserDelete.as_view(), name='system_user_del'),


    path('system-user-detail-<int:nid>.html', views.system_user_detail, name='system_user_detail'),
    path('system-user-update-<int:nid>.html', views.system_user_update, name='system_user_update'),

    path('api/asset.html',api.AssetList.as_view(),name='asset_api_list'),
    path('api/asset-detail-<int:pk>.html', api.AssetDetail.as_view(), name='asset_api_detail'),

    path('asset-export.html',views.export,name='asset_export'),
]


app_name="asset"

autoops/autoops/urls.py
from django.conf.urls import include,url
from django.contrib import admin

from names.views import index,login_view,logout
from django.conf.urls import handler404, handler500
from asset.views import  AssetUpload
from django.conf import settings
from django.urls  import path

import xadmin
xadmin.autodiscover()

from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    path('admin/', xadmin.site.urls, name="xadmin"),
    path('dadmin/', admin.site.urls,name="dadmin"),
    path('', index),
    path('login.html', login_view,name="login_view"),
    path('logout.html', logout,name="logout"),
    path('index.html', index),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    path('db/', include('db.urls', namespace="db", ), ),
    path('tasks/', include('tasks.urls', namespace="tasks",), ),
    path('names/', include('names.urls', namespace="names",), ),
    path('library/', include('library.urls', namespace="library",), ),
    path('upload/',  AssetUpload.as_view()),
    path('ueditor/',include('DjangoUeditor.urls' )),
    path('release/', include('release.urls', namespace="release")),
]



if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoops/db/urls.py
from django.urls  import path
from  .import views

urlpatterns = [
    path('db.html',views.DbListAll.as_view(),name='db_list'),
    path('db-add.html',views.DbAdd.as_view(),name='db_add'),
    path('db-del.html',views.DbDel.as_view(),name='db_del'),
    path('db-all-del.html',views.db_all_del,name='db_all_del'),
    path('db-update-<int:pk>.html', views.DbUpdate.as_view(), name='db_update'),
    path('asset-detail-<int:pk>.html',views.DbDetail.as_view(),name='db_detail'),




    path('db-user.html', views.DbUserListAll.as_view(), name='db_user_list'),
    path('db-user-add.html', views.DbUserAdd.as_view(), name='db_user_add'),
    path('db-user-update-<int:pk>.html', views.DbUserUpdate.as_view(), name='db_user_update'),
    path('db-user-del.html', views.DbUserDel.as_view(), name='db_del'),
    path('db-user-detail-<int:pk>.html', views.DbUserDetail.as_view(), name='db_user_detail'),
    path('db-user-db-<int:nid>.html', views.Db_user_db, name='db_user_db'),
]


app_name="db"

autoops/release/urls.py
from django.urls  import path

from  .import views

urlpatterns = [
    path('release.html',views.ReleaseListAll.as_view(),name='release_list'),
    path('release-add.html',views.ReleaseAdd.as_view(),name='release_add'),
    path('release-del.html',views.ReleaseDel.as_view(),name='release_del'),
    path('release-update-<int:pk>.html', views.ReleaseUpdate.as_view(), name='release_update'),
    path('release-upload-<int:pk>.html', views.ReleaseUpload.as_view(), name='release_upload'),
    path('release-upload.html', views.ReleaseUploadPost.as_view(), name='release_upload_post'),




]


app_name="release"

autoops/release/models.py
from django.db import models
import random


class codebase(models.Model):
    name = models.CharField(max_length=64, verbose_name='代码名称', null=True,blank=True)

    ps = models.CharField(max_length=1024,verbose_name="备注",null=True,blank=True)
    file = models.FileField(upload_to = 'codebase/%Y%m%d{}'.format(random.randint(0,99999)),verbose_name="代码文件",)


    ctime= models.DateTimeField(auto_now_add=True,null=True,verbose_name='创建时间',blank=True)
    utime = models.DateTimeField(auto_now=True, null=True,verbose_name='更新时间',blank=True)

    class  Meta:
        db_table ="codebase"
        verbose_name="代码"
        verbose_name_plural = '资产管理'

    def __str__(self):
        return self.name

autoops/release/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView, DeleteView, DetailView
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from .models import codebase
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from .form import CodeBaseForm
from guardian.shortcuts import get_objects_for_user, get_objects_for_group
import json,os

from django.contrib.auth.models import User
from guardian.decorators import permission_required_or_403
from asset.models import asset
from guardian.core import ObjectPermissionChecker
from names.password_crypt import decrypt_p
from tasks.models import history

from   tasks.ansible_2420.runner import AdHocRunner
from  tasks.ansible_2420.inventory import BaseInventory


class ReleaseListAll(TemplateView):
    model = codebase
    template_name = 'release/release.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ReleaseListAll, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "release_active": "active",
            "release_list_active": "active",
            'codebase_list': codebase.objects.all(),
        }
        kwargs.update(context)
        return super(ReleaseListAll, self).get_context_data(**kwargs)



class ReleaseAdd(CreateView):
    model = codebase
    form_class = CodeBaseForm
    template_name = 'release/release-add.html'
    success_url = reverse_lazy('release:release_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ReleaseAdd, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.asset_save = asset_save = form.save()
        return super(ReleaseAdd, self).form_valid(form)

    def get_success_url(self):
        return super(ReleaseAdd, self).get_success_url()

    def get_context_data(self, **kwargs):
        context = {
            "release_active": "active",
            "release_list_active": "active",
        }
        kwargs.update(context)
        return super(ReleaseAdd, self).get_context_data(**kwargs)



class ReleaseUpdate(UpdateView):
    model = codebase
    form_class = CodeBaseForm
    template_name = 'release/release-update.html'
    success_url = reverse_lazy('release:release_list')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ReleaseUpdate, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "release_active": "active",
            "release_list_active": "active",
        }
        kwargs.update(context)
        return super(ReleaseUpdate, self).get_context_data(**kwargs)

    def form_invalid(self, form):
        print(form.errors)
        return super(ReleaseUpdate, self).form_invalid(form)

    def form_valid(self, form):
        self.object = form.save()
        return super(ReleaseUpdate, self).form_valid(form)


    def get_success_url(self):
        return super(ReleaseUpdate, self).get_success_url()

class  ReleaseDel(View):
    model = codebase

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ReleaseDel, self).dispatch(*args, **kwargs)

    def post(self, request):
        ret = {'status': True, 'error': None, }
        try:
            id = request.POST.get('nid', None)
            print(id)
            c = codebase.objects.get(id=id)
            path = c.file.url
            print(path)
            path2 = path[1:]
            os.remove(path2)
            c.delete()

        except Exception as e:
            ret = {
                "static": False,
                "error": '删除请求错误,代码名称不能是中文{}'.format(e)
            }
        finally:
            return HttpResponse(json.dumps(ret))

class ReleaseUpload(View):
    model = codebase

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ReleaseUpload,self).dispatch(*args, **kwargs)

    def    get(self,request,pk):
        code_id = codebase.objects.filter(id=pk)
        obj = get_objects_for_user(self.request.user, 'asset.task_asset')
        return render(self.request, 'release/release-upload.html',
            { "release_active": "active",
            "release_list_active": "active",  "asset_list":obj, "code":code_id })

class ReleaseUploadPost(View):

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
            return super(ReleaseUploadPost, self).dispatch(*args, **kwargs)

    def   post(self,request):  ##命令行
            ids = request.POST.getlist('id')
            code_id = request.POST.get('code_id', None)
            dest = request.POST.get('dest',None)
            user = User.objects.get(username=request.user)
            checker = ObjectPermissionChecker(user)
            ids1 = []

            for i in ids:
                assets = asset.objects.get(id=i)
                if checker.has_perm('task_asset', assets, ) == True:
                    ids1.append(i)
                else:
                    error_3 = "主机没有权限"
                    ret = {"error": error_3, "status": False}
                    return HttpResponse(json.dumps(ret))

            idstring = ','.join(ids1)
            if not ids:
                error_1 = "请选择主机"
                ret = {"error": error_1, "status": False}
                return HttpResponse(json.dumps(ret))

            obj = asset.objects.extra(where=['id IN (' + idstring + ')'])
            ret = {'data': []}
            tasks = []

            file = codebase.objects.get(id=code_id)


            for i in obj:
                try:
                    assets = [
                        {
                            "hostname": 'host',
                            "ip": i.network_ip,
                            "port": i.port,
                            "username": i.system_user.username,
                            "password": decrypt_p(i.system_user.password),
                        },
                    ]
                    tasks = [
                        {"action": {"module": "copy", "args": "src=./upload/{0}   {1}".format(file.file.name,dest)}, "name": "copy_code"},
                    ]

                    inventory = BaseInventory(assets)
                    runner = AdHocRunner(inventory)
                    retsult = runner.run(tasks, "all")

                    ret1 = []

                    try:
                        ret1.append("分发成功 {}      备注：如果前面返回值为 false，表示已经分发完成了，请不要重复分发。".format(retsult.results_raw['ok']['host']['copy_code']['changed']))
                    except Exception as e:
                        if retsult.results_summary['dark'] == {}   :
                                ret1.append("执行成功")
                        else:
                                ret1.append("命令有问题,{}".format(retsult.results_summary['dark']))

                    history.objects.create(ip=i.network_ip, root=i.system_user, port=i.port, cmd="上传 {} 到 {}".format(file.name,dest), user=user)

                    ret2 = {'ip': i.network_ip, 'data': '\n'.join(ret1)}
                    ret['data'].append(ret2)
                except Exception as e:
                    ret['data'].append({"ip": i.network_ip, "data": "账号密码不对,{}".format(e)})



            return HttpResponse(json.dumps(ret))

autoops/templates/release/release-add.html
{% extends "base.html" %}
{% block  title %}资产添加{% endblock %}
{% block header-css %}
{% load	bootstrap3 %}
{% endblock %}


{% block page-content %}

    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>代码库添加</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                     <a href="{% url  'release:release_list'  %}">代码库管理</a>
                </li>
                <li class="active">
                    <strong>代码库添加</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>


    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-title">
                    <h3>代码库添加</h3>
                    <div style="color:red;">  {{ msg }}</div>
                    <div class="ibox-tools">
                        <a class="collapse-link">
                            <i class="fa fa-chevron-up"></i>
                        </a>
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            <i class="fa fa-wrench"></i>
                        </a>
                        <ul class="dropdown-menu dropdown-user">
                            <li><a href="#">选项 1</a>
                            </li>
                            <li><a href="#">选项 2</a>
                            </li>
                        </ul>
                        <a class="close-link">
                            <i class="fa fa-times"></i>
                        </a>
                    </div>
                </div>
                <div class="ibox-content">
                    <form class="form-horizontal" action="" method="post"
                          enctype="multipart/form-data">
                        {% csrf_token %}
                        {% if form.no_field_errors %}
                            <div class="alert alert-danger" style="margin: 20px auto 0px">
                                {{ form.non_field_errors }}
                            </div>
                        {% endif %}

                        <div class="form-group">
                            <div class="col-sm-10 col-sm-offset-0">
                                <h3>基本</h3>
                                {% bootstrap_field form.name layout="horizontal" %}
                                 {% bootstrap_field form.file   layout="horizontal"  %}
                             {% bootstrap_field form.ps layout="horizontal" %}
                            </div>
                        </div>
                        <div class="hr-line-dashed"></div>


                        <div class="form-group">
                            <div class="col-sm-4 col-sm-offset-3">

                                 {% bootstrap_button "保存" button_type="submit" button_class="btn-primary" %}
                                 {% bootstrap_button "重置" button_type="reset" button_class="btn btn-white" %}
                            </div>
                        </div>

                    </form>


                </div>
            </div>
        </div>

    </div>


    {% block footer-js %}



        <script>
            $(document).ready(function () {
                $('.select2').select2();
                {#            $("#id_tags").select2({#}
                {#                tags: true,#}
                {#                maximumSelectionLength: 8  //最多能够选择的个数#}
                {#                //closeOnSelect: false#}
                {#            });#}
            })
        </script>


    {% endblock %}



{% endblock %}

autoops/templates/release/release-upload.html
{% extends "base.html" %}

{% load  mytags %}
{% block  title %}脚本执行{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>代码分发</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>代码</a>
                </li>
                <li class="active">
                     <a href="{% url  'release:release_list'  %}">代码库管理</a>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
<div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-5">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>脚本执行</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">
                        <div class="table-responsive">
                            <form class="form-horizontal  cmd_from">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>外网IP</th>
                                        <th>管理IP</th>
                                        <th>用户</th>
                                        <th>产品线</th>

                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in   asset_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center"><a
                                                    href="{% url  "asset:asset_detail"   row.id %}">{{ row.network_ip }}</a>
                                            </td>
                                            <td class="center">{{ row.manage_ip }}</td>
                                             <td class="center">{{ row.system_user }}</td>
                                            <td class="center">{{ row.product_line }}
                                                </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>
                                <div class="ibox-content">
                             {%  for row in code %}
                                   <div class="form-group"><label class="col-sm-2 control-label">代码库</label>
                           <input type="text"   name="code_id" style="display:none"    value="{{ row.id }}"/>
                                <div class="col-lg-4 col-sm-6" >  {{ row.name }} &nbsp; ----- &nbsp;{{ row.file.name  | lowers   }}
                                </div>
                            </div>


                                    {% endfor %}

                                   <div class="form-group"><label class="col-sm-2 control-label">目标目录</label>
                                <div class="col-lg-9 col-sm-6"><input type="text" class="form-control" name="dest"  required=""     value="dest=" >
                                </div>
                            </div>

                            <div class="hr-line-dashed"></div>



                                    <div class="form-group">
                                        <div class="col-sm-6 col-sm-offset-2">

                                            <a id="cmd" class="btn btn-primary" type="submit">提交</a>
                                            <button class="btn btn-white" type="button" onclick='clearBody()'>取消
                                            </button>
                                        </div>
                                    </div>

                                </div>

                            </form>
                        </div>

                    </div>
                </div>
            </div>
            <div class="col-sm-7">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>输出结果
                        </h5>
                        <div class="ibox-tools">
                            <a class="collapse-links">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">配置选项 1</a>
                                </li>
                                <li><a href="#">配置选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content  pres"><pre><span id="err"></span></pre>
                    </div>


                                        <div class="ibox-content"   >

                          <pre>
copy：复制文件

	* src:本地源文件路径
	* content:表示直接用此处 指定的内容 生成为目标文件内容
	* dest: 远程目标文件路径
	* force:当设置为yes时，如果目标主机存在该文件，但内容不同，会强制覆盖。默认为yes。
	* backup:在覆盖之前备份源文件，yes/no


ansible all -m copy -a 'src=/root/test.ansible dest=/tmp/'
ansible all -m copy -a 'src=/root/test.ansible dest=/tmp/  owner=root group=root mode=644 backup=yes'
例如：
目标目录    dest=/tmp/  owner=root group=root mode=644 backup=yes


                    </div>
                </div>
            </div>
        </div>
    </div>



{% block footer-js %}      <script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>

<script>


    $(function () {


        $('#cmd').click(function () {
            $.ajax({
                url: "/release/release-upload.html",
                type: 'POST',
                data: $('.cmd_from').serialize(),
                success: function (data) {
                    var obj = JSON.parse(data);
                    cons = "";
                    if (obj.data) {

                         $.each(obj, function (data, values) {
                            $.each(values, function (index, value) {
                                cons += "<pre>"+"主机:" + value.ip + "\n" + "结果: \n " + value.data + "</pre>"

                            });
                            $(".pres").html(cons); //把内容入到这个div中即完成
                        });

                    } else {
                        $('#err').text(obj.error);
                    }

                }

            })
        });





    });

    function clearBody() {
        location.reload()
    }

</script>


{% endblock %}

{% endblock %}

autoops/templates/release/release.html
{% extends "base.html" %}
{% load  mytags %}

{% block  title %}资产信息{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>代码库</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="{% url  'release:release_list'  %}">代码库管理</a>
                </li>
                <li class="active">
                    <strong>代码库</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>代码库</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <a href="{% url    'release:release_add' %}" class="btn btn-primary  ">
                                添加</a>

                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                <tr>
                                    <th>名称</th>
                                    <th>代码名称</th>
                                    <th>备注</th>
                                    <th>创建时间</th>
                                    <th>更新时间</th>
                                    <th>动作</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for   row   in   codebase_list %}
                                    <tr class="gradeA" id="{{ row.id }}">
                                        <td class="center">{{ row.name }}
                                        </td>
                                        <td><b>  {% if  row.file %}
                                                <a href="{{ row.file.url }} ">{{ row.file.name | lowers }}</a> {% endif %}
                                            </b></td>

                                        <td class="center">{{ row.ps }}</td>
                                    <td class="center">{{ row.ctime }}</td>
                                    <td class="center">{{ row.utime }}</td>

                                        <td><a class="btn btn-primary  btn-xs"
                                               href="{% url  "release:release_update"   row.id %}">编辑</a>

                                            <a class="btn btn-primary  btn-xs"
                                               href="{% url  "release:release_upload"   row.id     %}">分发</a>



                                            <button class="btn btn-danger  btn-xs  system_user_del"
                                                 >删除
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>名称</th>
                                    <th>代码库名称</th>
                                    <th>备注</th>
                                    <th>创建时间</th>
                                    <th>更新时间</th>
                                    <th>动作</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>



    {% block footer-js %}      <script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>
        <script>
            $(function () {
  $(document).on('click','.system_user_del',function () {

                    var id = $(this).parent().parent().attr('id');

                    swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {
                        $.ajax({
                              url: "/release/release-del.html",
                             type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        });


                    });
                });



                });


        </script>


    {% endblock %}

{% endblock %}