autoops/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

autoops/asset/urls.py
from django.urls  import path
from . import api
from  .import views

urlpatterns = [
    path('asset.html',views.AssetListAll.as_view(),name='asset_list'),
    path('asset-add.html',views.AssetAdd.as_view(),name='asset_add'),
    path('asset-del.html',views.AssetDel.as_view(),name='asset_del'),
    path('asset-all-del.html',views.AssetAllDel.as_view(),name='asset_all_del'),
    path('asset-detail-<int:pk>.html',views.AssetDetail.as_view(),name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),




    path('asset-hardware-update.html', views.asset_hardware_update, name='asset_hardware_update'),
    path('asset-performance-<int:nid>.html', views.asset_performance, name='asset_performance'),
    path('asset-webssh.html', views.asset_web_ssh, name='asset_web_ssh'),

    path('system-user.html', views.SystemUserListAll.as_view(), name='system_user'),
    path('system-user-asset-<int:nid>.html', views.system_user_asset, name='system_user_asset'),
    path('system-user-add.html', views.system_user_add, name='system_user_add'),

    path('system-user-del.html', views.SystemUserDelete.as_view(), name='system_user_del'),


    path('system-user-detail-<int:nid>.html', views.system_user_detail, name='system_user_detail'),
    path('system-user-update-<int:nid>.html', views.system_user_update, name='system_user_update'),

    path('api/asset.html',api.AssetList.as_view(),name='asset_api_list'),
    path('api/asset-detail-<int:pk>.html', api.AssetDetail.as_view(), name='asset_api_detail'),

    path('asset-export.html',views.export,name='asset_export'),
]


app_name="asset"

autoops/autoops/urls.py
from django.conf.urls import include,url
from django.contrib import admin

from names.views import index,login_view,logout
from django.conf.urls import handler404, handler500
from asset.views import  AssetUpload
from django.conf import settings
from django.urls  import path

import xadmin
xadmin.autodiscover()

from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    path('admin/', xadmin.site.urls, name="xadmin"),
    path('dadmin/', admin.site.urls,name="dadmin"),
    path('', index),
    path('login.html', login_view,name="login_view"),
    path('logout.html', logout,name="logout"),
    path('index.html', index),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    path('db/', include('db.urls', namespace="db", ), ),
    path('tasks/', include('tasks.urls', namespace="tasks",), ),
    path('names/', include('names.urls', namespace="names",), ),
    path('library/', include('library.urls', namespace="library",), ),
    path('upload/',  AssetUpload.as_view()),
    path('ueditor/',include('DjangoUeditor.urls' )),
    path('release/', include('release.urls', namespace="release")),
]



if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoops/db/urls.py
from django.urls  import path
from  .import views

urlpatterns = [
    path('db.html',views.DbListAll.as_view(),name='db_list'),
    path('db-add.html',views.DbAdd.as_view(),name='db_add'),
    path('db-del.html',views.DbDel.as_view(),name='db_del'),
    path('db-all-del.html',views.db_all_del,name='db_all_del'),
    path('db-update-<int:pk>.html', views.DbUpdate.as_view(), name='db_update'),
    path('asset-detail-<int:pk>.html',views.DbDetail.as_view(),name='db_detail'),




    path('db-user.html', views.DbUserListAll.as_view(), name='db_user_list'),
    path('db-user-add.html', views.DbUserAdd.as_view(), name='db_user_add'),
    path('db-user-update-<int:pk>.html', views.DbUserUpdate.as_view(), name='db_user_update'),
    path('db-user-del.html', views.DbUserDel.as_view(), name='db_del'),
    path('db-user-detail-<int:pk>.html', views.DbUserDetail.as_view(), name='db_user_detail'),
    path('db-user-db-<int:nid>.html', views.Db_user_db, name='db_user_db'),
]


app_name="db"

autoops/db/models.py
from django.db import models
from django.contrib.auth.models import Group



class db_mysql(models.Model):

    hostname = models.CharField(max_length=64, verbose_name='数据库名字',unique=True)
    ip = models.GenericIPAddressField(verbose_name='IP', null=True,blank=True)
    port = models.IntegerField(verbose_name='端口', null=True,blank=True,default="3306")
    model = models.CharField(max_length=128, verbose_name='数据库型号', null=True,blank=True)


    db_user = models.ForeignKey(to="db_user", to_field='id', on_delete=models.SET_NULL, null=True,
                                    verbose_name='数据库登陆用户', blank=True)


    product_line =  models.ForeignKey(to=Group,to_field='id',on_delete=models.SET_NULL,verbose_name='产品线',null=True)
    data_center = models.ForeignKey(to="asset.data_centers", to_field='id', on_delete=models.SET_NULL, null=True,
                                    verbose_name='数据中心',blank=True)



    is_active = models.BooleanField(default=True, verbose_name=('是否启用'))



    ps = models.CharField(max_length=1024,verbose_name="备注",null=True,blank=True)

    ctime= models.DateTimeField(auto_now_add=True,null=True,verbose_name='创建时间',blank=True)
    utime = models.DateTimeField(auto_now=True, null=True,verbose_name='更新时间',blank=True)


    class  Meta:
        db_table ="db_mysql"
        verbose_name="数据库管理"
        verbose_name_plural = '数据库管理'
        permissions = {
            ('read_db_mysql',u"只读数据库资产"),
            ('task_db_mysql', u"执行数据库资产"),
        }


    def __str__(self):
        return self.hostname



class  db_user(models.Model):

    name = models.CharField(max_length=128, unique=True,verbose_name='名称')
    username = models.CharField(max_length=64,null=True,blank=True, default='root',verbose_name=('登陆用户'))
    password =  models.CharField(max_length=255, blank=True,null=True,verbose_name=('登陆密码'))
    product_line = models.ForeignKey(to=Group, to_field='id', on_delete=models.SET_NULL, verbose_name='产品线',null=True)
    ps = models.CharField(max_length=1024,verbose_name="备注",null=True,blank=True)
    ctime= models.DateTimeField(auto_now_add=True,null=True,verbose_name='创建时间',blank=True)
    utime = models.DateTimeField(auto_now=True, null=True,verbose_name='更新时间',blank=True)



    def __str__(self):
        return self.name

    class  Meta:
        db_table ="db_user"
        verbose_name="数据库登陆用户"
        verbose_name_plural = '数据库登陆用户'
        permissions = {
            ('read_db_user',u"只读系统登陆用户"),
        }

autoops/db/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from db.models import db_user,db_mysql
from .form import DbMysqlForm,DbUsersForm
from names.password_crypt import encrypt_p,decrypt_p

from django.contrib.auth.models import User, Group
from guardian.shortcuts import assign_perm, get_perms
from guardian.core import ObjectPermissionChecker
from guardian.decorators import permission_required_or_403

from guardian.shortcuts import get_objects_for_user, get_objects_for_group
from guardian.models import UserObjectPermission, GroupObjectPermission
from django.views.generic import TemplateView, ListView, View, CreateView, UpdateView, DeleteView, DetailView
from django.urls import reverse_lazy


from django.db.models import Q
import xlwt, time, json




class DbListAll(TemplateView):
    template_name = 'db/db.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DbListAll, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "db_active": "active",
            "db_list_active": "active",
            'db_list': get_objects_for_user(self.request.user, 'db.read_db_mysql')
        }
        kwargs.update(context)
        return super(DbListAll, self).get_context_data(**kwargs)



class DbDetail(DetailView):
    model = db_mysql
    template_name = 'db/db-detail.html'

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('db.read_db_mysql', (db_mysql, 'id', 'pk')))
    def dispatch(self, *args, **kwargs):
        return super(DbDetail, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        pk = self.kwargs.get(self.pk_url_kwarg, None)
        detail = db_mysql.objects.get(id=pk)

        context = {
            "db_active": "active",
            "db_list_active": "active",
            "dbs": detail,
            "nid": pk,
        }
        kwargs.update(context)
        return super(DbDetail, self).get_context_data(**kwargs)



class DbAdd(CreateView):
    model = db_mysql
    form_class =  DbMysqlForm
    template_name = 'db/db-add.html'
    success_url = reverse_lazy('db:db_list')

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('db.add_db_mysql'))
    def dispatch(self, *args, **kwargs):
        return super(DbAdd, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.db = db =  form.save()

        myproduct = form.cleaned_data['product_line']
        mygroup = Group.objects.get(name=myproduct)
        GroupObjectPermission.objects.assign_perm("read_db_mysql", mygroup, obj=db)
        GroupObjectPermission.objects.assign_perm("add_db_mysql", mygroup, obj=db)
        GroupObjectPermission.objects.assign_perm("change_db_mysql", mygroup, obj=db)
        GroupObjectPermission.objects.assign_perm("delete_db_mysql", mygroup, obj=db)
        GroupObjectPermission.objects.assign_perm("task_db_mysql", mygroup, obj=db)
        return super(DbAdd, self).form_valid(form)

    def get_success_url(self):
        return super(DbAdd, self).get_success_url()

    def get_context_data(self, **kwargs):
        context = {
            "db_active": "active",
            "db_list_active": "active",
        }
        kwargs.update(context)
        return super(DbAdd, self).get_context_data(**kwargs)



class DbUpdate(UpdateView):
    model = db_mysql
    form_class = DbMysqlForm
    template_name = 'db/db-update.html'
    success_url = reverse_lazy('db:db_list')

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('db.change_db_mysql', (db_mysql, 'id', 'pk')))
    def dispatch(self, *args, **kwargs):
        return super(DbUpdate, self).dispatch(*args, **kwargs)



    def get_context_data(self, **kwargs):
        context = {
            "db_active": "active",
            "db_list_active": "active",
        }
        kwargs.update(context)
        return super(DbUpdate, self).get_context_data(**kwargs)


    def form_invalid(self, form):
        print(form.errors)
        return super(DbUpdate, self).form_invalid(form)



    def form_valid(self, form):

        pk = self.kwargs.get(self.pk_url_kwarg, None)
        old_myproduct = db_mysql.objects.get(id=pk).product_line
        old_mygroup = Group.objects.get(name=old_myproduct)
        new_mygroup = Group.objects.get(name=form.cleaned_data['product_line'])

        self.object = form.save()
        if old_mygroup != new_mygroup:
            GroupObjectPermission.objects.remove_perm("read_db_mysql", old_mygroup, obj=self.object)
            GroupObjectPermission.objects.remove_perm("add_db_mysql", old_mygroup, obj=self.object)
            GroupObjectPermission.objects.remove_perm("change_db_mysql", old_mygroup, obj=self.object)
            GroupObjectPermission.objects.remove_perm("delete_db_mysql", old_mygroup, obj=self.object)
            GroupObjectPermission.objects.remove_perm("task_db_mysql",old_mygroup, obj=self.object)


            GroupObjectPermission.objects.assign_perm("read_db_mysql", new_mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("add_db_mysql", new_mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("change_db_mysql", new_mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("delete_db_mysql", new_mygroup, obj=self.object)
            GroupObjectPermission.objects.assign_perm("task_db_mysql",new_mygroup, obj=self.object)

        return super(DbUpdate, self).form_valid(form)

    def get_success_url(self):
        return super(DbUpdate, self).get_success_url()




class DbDel(View):
    model = db_mysql

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DbDel, self).dispatch(*args, **kwargs)

    def post(self, request):
        ret = {'status': True, 'error': None, }
        try:
            id = request.POST.get('nid', None)
            dbs = db_mysql.objects.get(id=id)
            user = User.objects.get(username=request.user)

            checker = ObjectPermissionChecker(user)
            if checker.has_perm('delete_asset', dbs) == True:
                dbs.delete()

        except Exception as e:
            ret = {
                "static": False,
                "error": '删除请求错误,{}'.format(e)
            }
        finally:
             return HttpResponse(json.dumps(ret))



@login_required(login_url="/login.html")
def db_all_del(request):
    ret = {'status': True, 'error': None, }
    if request.method == "POST":
        try:
            ids = request.POST.getlist('id', None)
            ids1 = []
            for i in ids:
                user = User.objects.get(username=request.user)
                checker = ObjectPermissionChecker(user)
                assets = db_mysql.objects.get(id=i)
                if checker.has_perm('delete_db', assets, ) == True:
                    ids1.append(i)

            idstring = ','.join(ids1)
            db_mysql.objects.extra(where=['id IN (' + idstring + ')']).delete()


        except Exception as e:
            ret['status'] = False
            ret['error'] = '删除请求错误,{}'.format(e)
        finally:
              return HttpResponse(json.dumps(ret))

class DbUserListAll(TemplateView):
    template_name = 'db/db-user.html'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(DbUserListAll, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = {
            "db_active": "active",
            "db_user_active": "active",
            'db_user_list': get_objects_for_user(self.request.user, 'db.read_db_user')
        }
        kwargs.update(context)
        return super(DbUserListAll, self).get_context_data(**kwargs)



class DbUserAdd(CreateView):
    model = db_user
    form_class =  DbUsersForm
    template_name = 'db/db-user-add.html'
    success_url = reverse_lazy('db:db_user_list')

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('db.add_db_user'))
    def dispatch(self, *args, **kwargs):
        return super(DbUserAdd, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.db = db = form.save()

        password1 = encrypt_p(form.cleaned_data['password'])
        db.password = password1
        db.save()

        myproduct =form.cleaned_data['product_line']
        mygroup = Group.objects.get(name=myproduct)
        GroupObjectPermission.objects.assign_perm("read_db_user", mygroup, obj=db)
        GroupObjectPermission.objects.assign_perm("add_db_user", mygroup, obj=db)
        GroupObjectPermission.objects.assign_perm("change_db_user", mygroup, obj=db)
        GroupObjectPermission.objects.assign_perm("delete_db_user", mygroup, obj=db)

        return super(DbUserAdd, self).form_valid(form)

    def get_success_url(self):
        return super(DbUserAdd, self).get_success_url()

    def get_context_data(self, **kwargs):
        context = {
            "db_active": "active",
            "db_user_active": "active",
        }
        kwargs.update(context)
        return super(DbUserAdd, self).get_context_data(**kwargs)


class DbUserUpdate(UpdateView):
    model = db_user
    form_class = DbUsersForm
    template_name = 'db/db-user-update.html'
    success_url = reverse_lazy('db:db_user_list')

    @method_decorator(login_required)
    @method_decorator(permission_required_or_403('db.change_db_user', (db_user, 'id', 'pk')))
    def dispatch(self, *args, **kwargs):
        return super(DbUserUpdate, self).dispatch(*args, **kwargs)



    def get_context_data(self, **kwargs):
        context = {
            "db_active": "active",
            "db_user_active": "active",
        }
        kwargs.update(context)

autoops/templates/db/db-user.html
{% extends "base.html" %}


{% block  title %}数据库信息{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>数据库用户信息</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a href="/db/db-user.html">数据库用户管理</a>
                </li>
                <li class="active">
                    <strong>数据库用户信息</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>数据库用户信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">

                            <a href="{% url    'db:db_user_add' %}" class="btn btn-primary  ">
                                添加</a>

                            <table class="table table-striped table-bordered table-hover dataTables-example">
                                <thead>
                                <tr>
                                    <th>名称</th>
                                    <th>系统用户</th>
                                     <th>产品线</th>
                                    <th>备注</th>
                                    <th>动作</th>
                                </tr>
                                </thead>
                                <tbody>

                                {% for   row   in  db_user_list %}
                                    <tr class="gradeA" id="{{ row.id }}">
                                        <td class="center"><a  href="{% url  "db:db_user_detail"   pk=row.id %}">  {{ row.name }}</a>
                                        </td>
                                        <td class="center">{{ row.username }}</td>
                                        <td class="center">{{ row.product_line }}</td>
                                        <td class="center">{{ row.ps }}</td>
                                        <td><a class="btn btn-primary  btn-xs"
                                               href="{% url  "db:db_user_update"   row.id %}" >编辑</a>
                                            <button class="btn btn-danger  btn-xs  db_user_del"

                                                    >删除
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor %}

                                </tbody>
                                <tfoot>
                                <tr>
                                    <th>名称</th>
                                    <th>系统用户</th>
                                     <th>产品线</th>
                                    <th>备注</th>
                                    <th>动作</th>
                                </tr>
                                </tfoot>
                            </table>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>




    {% block footer-js %}

              <script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>


        <script>
            $(function () {

                $('.db_user_del').click(function () {
                    var id = $(this).parent().parent().attr('id');

                        swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {


                    $.ajax({
                        url: "/db/db-user-del.html",
                        type: 'POST',
                       data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                        }
                    })
                });
 });

            });
        </script>


    {% endblock %}

{% endblock %}

autoops/templates/db/db.html
{% extends "base.html" %}


{% block  title %}数据库信息{% endblock %}

{% block page-content %}


    <div class="row wrapper border-bottom white-bg page-heading">
        <div class="col-lg-10">
            <h2>数据库信息</h2>
            <ol class="breadcrumb">
                <li>
                    <a href="/index.html">主页</a>
                </li>
                <li>
                    <a>数据库管理</a>
                </li>
                <li class="active">
                    <strong>数据库信息</strong>
                </li>
            </ol>
        </div>
        <div class="col-lg-2">

        </div>
    </div>
    <div class="wrapper wrapper-content animated fadeInRight">
        <div class="row">
            <div class="col-lg-12">
                <div class="ibox float-e-margins">
                    <div class="ibox-title">
                        <h5>数据库信息</h5>
                        <div class="ibox-tools">
                            <a class="collapse-link">
                                <i class="fa fa-chevron-up"></i>
                            </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                            <ul class="dropdown-menu dropdown-user">
                                <li><a href="#">选项 1</a>
                                </li>
                                <li><a href="#">选项 2</a>
                                </li>
                            </ul>
                            <a class="close-link">
                                <i class="fa fa-times"></i>
                            </a>
                        </div>
                    </div>
                    <div class="ibox-content">

                        <div class="table-responsive">


                            <a href="{% url    'db:db_add' %}" class="btn btn-primary  ">
                                添加</a>

                            <a class="btn btn-danger  db_all_del"
                               >批量删除
                            </a>
                            {#                                <a href="{% url    'asset:asset_export' %}" class="btn btn-primary  ">#}
                            {#                                    导出全部</a>#}


                            <form id="del_form_db_all" class="form-horizontal  ">
                                <table class="table table-striped table-bordered table-hover dataTables-example">
                                    <thead>
                                    <tr>
                                        <th width="20"><input type="checkbox" id="CheckedAll"></th>
                                        <th>名字</th>
                                        <th>IP</th>
                                        <th>产品线</th>

                                        <th>型号</th>
                                        <th>端口</th>
                                        <th>登陆用户</th>

                                        <th>动作{{ error_performance }}</th>
                                    </tr>
                                    </thead>
                                    <tbody>

                                    {% for   row   in  db_list %}

                                        <tr class="gradeA" id="{{ row.id }}">
                                            <td><input type="checkbox" value="{{ row.id }}" name="id"></td>
                                            <td class="center">
                                                <a href="{% url  "db:db_detail"   pk=row.id %}">{{ row.hostname }}</a>
                                            </td>
                                            </td>
                                            <td class="center">{{ row.ip }}</td>
                                            <td class="center">{{ row.product_line.name }}</td>

                                            <td class="center">{{ row.model }}</td>
                                            <td class="center">{{ row.port }}</td>
                                            <td class="center">{{ row.db_user }}</td>

                                            <td><a class="btn btn-primary  btn-xs "
                                                   href="{% url  "db:db_update"  pk=row.id %}">编辑</a>
                                                <a class="btn btn-danger  btn-xs  db_del"
                                                >删除
                                                </a>

                                            </td>
                                        </tr>
                                    {% endfor %}

                                    </tbody>

                                </table>
                            </form>


                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>



    {% block footer-js %}


              <script type="text/JavaScript">
    $.ajaxSetup({headers: {"X-CSRFToken": '{{ csrf_token }}'}});
</script>


        <script>
            $(function () {
  $(document).on('click','.db_del',function () {

                    var id = $(this).parent().parent().attr('id');

                    swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",
                        closeOnConfirm: false
                    }, function () {

                        $.ajax({
                            url: "/db/db-del.html",
                            type: 'POST',
                            data: {'nid': id},
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }
                        })
                    });
                });

  $(document).on('click','.db_all_del',function () {


                    swal({

                        title: "你确定删除",
                        text: "你将无法恢复",
                        type: "warning",
                        showCancelButton: true,
                        confirmButtonColor: "#DD6B55",
                        confirmButtonText: "确定",

                        closeOnConfirm: false
                    }, function () {


                        $.ajax({
                            url: "/db/db-all-del.html",
                            type: 'POST',
                            data: $('#del_form_db_all').serialize(),
                            success: function (data) {
                                var obj = JSON.parse(data);
                                if (obj.status) {
                                    swal({title: "删除", text: "已成功删除", type: "success"}, function () {
                                        window.location.reload();
                                    })
                                } else {
                                    swal("错误", "删除" + "[ " + obj.error + " ]" + "遇到错误", "error");
                                }
                            }

                        })
                    });


                });

            });


        </script>


    {% endblock %}

{% endblock %}