autoops/DjangoUeditor/urls.py
# -*- coding: utf-8 -*-
import django
from .views import get_ueditor_controller

DJANGO_VERSION = django.VERSION[:2]


if DJANGO_VERSION >= (1, 8):
    from django.conf.urls import url
    urlpatterns = [
        url(r'^controller/$', get_ueditor_controller)
    ]

else:
    try:
        from django.conf.urls import patterns, url
    except ImportError:
        from django.conf.urls.defaults import patterns, url

    urlpatterns = patterns('',
        url(r'^controller/$', get_ueditor_controller)
    )

autoops/asset/urls.py
from django.urls  import path
from . import api
from  .import views

urlpatterns = [
    path('asset.html',views.AssetListAll.as_view(),name='asset_list'),
    path('asset-add.html',views.AssetAdd.as_view(),name='asset_add'),
    path('asset-del.html',views.AssetDel.as_view(),name='asset_del'),
    path('asset-all-del.html',views.AssetAllDel.as_view(),name='asset_all_del'),
    path('asset-detail-<int:pk>.html',views.AssetDetail.as_view(),name='asset_detail'),
    path('asset-update-<int:pk>.html', views.AssetUpdate.as_view(), name='asset_update'),




    path('asset-hardware-update.html', views.asset_hardware_update, name='asset_hardware_update'),
    path('asset-performance-<int:nid>.html', views.asset_performance, name='asset_performance'),
    path('asset-webssh.html', views.asset_web_ssh, name='asset_web_ssh'),

    path('system-user.html', views.SystemUserListAll.as_view(), name='system_user'),
    path('system-user-asset-<int:nid>.html', views.system_user_asset, name='system_user_asset'),
    path('system-user-add.html', views.system_user_add, name='system_user_add'),

    path('system-user-del.html', views.SystemUserDelete.as_view(), name='system_user_del'),


    path('system-user-detail-<int:nid>.html', views.system_user_detail, name='system_user_detail'),
    path('system-user-update-<int:nid>.html', views.system_user_update, name='system_user_update'),

    path('api/asset.html',api.AssetList.as_view(),name='asset_api_list'),
    path('api/asset-detail-<int:pk>.html', api.AssetDetail.as_view(), name='asset_api_detail'),

    path('asset-export.html',views.export,name='asset_export'),
]


app_name="asset"

autoops/autoops/urls.py
from django.conf.urls import include,url
from django.contrib import admin

from names.views import index,login_view,logout
from django.conf.urls import handler404, handler500
from asset.views import  AssetUpload
from django.conf import settings
from django.urls  import path

import xadmin
xadmin.autodiscover()

from xadmin.plugins import xversion
xversion.register_models()


urlpatterns = [
    path('admin/', xadmin.site.urls, name="xadmin"),
    path('dadmin/', admin.site.urls,name="dadmin"),
    path('', index),
    path('login.html', login_view,name="login_view"),
    path('logout.html', logout,name="logout"),
    path('index.html', index),
    path('asset/', include('asset.urls', namespace="asset", ), ),
    path('db/', include('db.urls', namespace="db", ), ),
    path('tasks/', include('tasks.urls', namespace="tasks",), ),
    path('names/', include('names.urls', namespace="names",), ),
    path('library/', include('library.urls', namespace="library",), ),
    path('upload/',  AssetUpload.as_view()),
    path('ueditor/',include('DjangoUeditor.urls' )),
    path('release/', include('release.urls', namespace="release")),
]



if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

autoops/db/urls.py
from django.urls  import path
from  .import views

urlpatterns = [
    path('db.html',views.DbListAll.as_view(),name='db_list'),
    path('db-add.html',views.DbAdd.as_view(),name='db_add'),
    path('db-del.html',views.DbDel.as_view(),name='db_del'),
    path('db-all-del.html',views.db_all_del,name='db_all_del'),
    path('db-update-<int:pk>.html', views.DbUpdate.as_view(), name='db_update'),
    path('asset-detail-<int:pk>.html',views.DbDetail.as_view(),name='db_detail'),




    path('db-user.html', views.DbUserListAll.as_view(), name='db_user_list'),
    path('db-user-add.html', views.DbUserAdd.as_view(), name='db_user_add'),
    path('db-user-update-<int:pk>.html', views.DbUserUpdate.as_view(), name='db_user_update'),
    path('db-user-del.html', views.DbUserDel.as_view(), name='db_del'),
    path('db-user-detail-<int:pk>.html', views.DbUserDetail.as_view(), name='db_user_detail'),
    path('db-user-db-<int:nid>.html', views.Db_user_db, name='db_user_db'),
]


app_name="db"

autoops/library/urls.py
from django.urls  import path

from  .import views

urlpatterns = [
    path('library.html', views.LibraryListAll.as_view(), name='library_list'),
    path('library-add.html', views.LibraryAdd.as_view(), name='library_add'),
    path('library-update-<int:pk>.html', views.LibraryUpdate.as_view(), name='library_update'),
    path('library-del.html',views.LibraryDel.as_view(),name='library_del'),
    path('library-detail-<int:pk>.html', views.LibraryDetail.as_view(), name='library_detail'),
]



app_name="library"

autoops/names/urls.py
from django.urls  import path

from  .import views

urlpatterns = [
    path('login-history.html',views.login_history,name="login_history"),
    path('password.html', views.password_update, name="password_update"),
    path('web-history.html', views.web_historys, name='web_history'),
    path('cmd-history.html', views.cmd_historys, name='cmd_history'),
]


app_name = "names"

autoops/tasks/urls.py
from django.urls  import path

from  .import views

urlpatterns = [
    path('cmd.html', views.cmd, name='cmd'),

    path('tools.html', views.ToolsListAll.as_view(), name='tools'),
    path('tools-add.html', views.tools_add, name='tools_add'),
    path('tools-del.html', views.tools_delete, name='tools_delete'),
    path('tools-bulk-del.html', views.tools_bulk_delte, name='tools_bulk_delte'),
    path('tools-update-<int:nid>.html', views.tools_update, name='tools_update'),
    path('tools-script-<int:nid>.html', views.tools_script_get, name='tools_script_get'),
    path('tools-script.html', views.tools_script_post, name='tools_script_post'),


    path('Inception.html', views.Inception, name='Inception'),
    path('Inception-exe.html', views.Inception_exe, name='Inception_exe'),
    path('Inception-rb.html', views.Inception_rb, name='Inception_rb'),
    path('Inception-query.html', views.Inception_query, name='Inception_query'),
    path('Inception-query-databases.html', views.Inception_query_databases, name='Inception_query_databases'),
]

app_name="tasks"

autoops/templates/_css.html
{% load  static %}

<link href=" {% static  "css/bootstrap.min.css" %}" rel="stylesheet">
<link href="{% static  "font-awesome/css/font-awesome.css" %}" rel="stylesheet">

<link href="{% static  "css/animate.css" %}" rel="stylesheet">
<link href="{% static "css/style.css"  %} " rel="stylesheet">

<link href="{% static "css/datatables.min.css"%} "   rel="stylesheet">

<link href="{% static "css/plugins/select2/select2.min.css"%} "   rel="stylesheet">



<link href="{% static  "css/plugins/sweetalert/sweetalert.css"%}" rel="stylesheet">

<link href="{% static "css/animate.css"%}" rel="stylesheet">
<link href="{% static "css/style.css"%}" rel="stylesheet">


<!-- Toastr style -->
<link  href="{% static  "css/plugins/toastr/toastr.min.css" %}"  rel="stylesheet">

autoops/templates/_footer.html
  <div class="footer">
            <div class="pull-right">
               <strong>QQ群: 620176501</strong>
            </div>
            <div>
                <strong>Copyright</strong> Example Company &copy; 2017-2020
            </div>
        </div>

autoops/templates/_js.html
{% load  static %}

<script src="{% static  "js/jquery-3.1.1.min.js"%}"></script>
<script src="{% static  "js/bootstrap.min.js"%}"></script>
<script src="{% static  "js/plugins/metisMenu/jquery.metisMenu.js"%}"></script>
<script src="{% static  "js/plugins/slimscroll/jquery.slimscroll.min.js"%}"></script>

<!-- Custom and plugin javascript -->
<script src="{% static  "js/inspinia.js"%} "></script>
<script src="{% static  "js/plugins/pace/pace.min.js"%}"></script>


<script src="{% static  "js/datatables.min.js" %}"></script>


<script src="{% static  "js/plugins/select2/select2.full.min.js" %}"></script>


<!-- Sweet alert -->
<script src="{% static  "js/plugins/sweetalert/sweetalert.min.js" %}"></script>

 <!-- Toastr script -->
<script src="{% static  "js/plugins/toastr/toastr.min.js"%}"></script>







<!-- Page-Level Scripts -->
<script>
   $(document).ready(function () {
        $('.dataTables-example').DataTable({

            "oLanguage": {
                "sLengthMenu": "每页显示 _MENU_ 条记录",
                "sZeroRecords": "对不起，查询不到任何相关数据",
                "sInfo": "当前显示 _START_ 到 _END_ 条，共 _TOTAL_条记录",
                "sInfoEmtpy": "找不到相关数据",
                "sInfoFiltered": " 数据表中共为 _MAX_ 条记录",
                "sProcessing": "正在加载中...",
                "sSearch": "搜索",
                "oPaginate": {
                    "sFirst": "第一页",
                    "sPrevious": " 上一页 ",
                    "sNext": " 下一页 ",
                    "sLast": " 最后一页 "
                }
            },
            "order": [[1, 'desc']],
            destroy:true,
            columnDefs: [{
                'targets': [0],    //都默认不排序
                'orderable': false
            }],


            dom: '<"html5buttons"B>lTfgitp,',

            buttons: [],
            lengthMenu: [[10, 25, 50, -1], [10, 25, 50, "全部"]]
        });


    });


       $("#CheckedAll").click(function () {
        if ($(this).is(":checked")) {
            $("[name=id]:checkbox").prop("checked", true);
        } else {
            $("[name=id]:checkbox").prop("checked", false);
        }
    });





    </script>

autoops/templates/_nav.html
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element">
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong
                                    class="font-bold">{{ user }}</strong>

                             </span> <span class="text-muted text-xs block">
                                {% ifequal  user.is_superuser  1 %}
                                    管理员 {% else %} 普通用户 {% endifequal %}
                                <b class="caret"></b></span> </span>
                    </a>
                    <ul class="dropdown-menu animated fadeInRight m-t-xs">
                        <li><a href="{% url  "names:password_update" %}">修改密码</a></li>
                        <li><a href="/logout.html">登出</a></li>
                    </ul>
                </div>
                <div class="logo-element">
                    Ops
                </div>
            </li>
            <li>
                <a href="/index.html"><i class="fa fa-th-list"></i> <span class="nav-label">首页</span>
                </a>

            </li>
            <li class="{{ asset_active }}">
                <a href="#"><i class="fa fa-drivers-license"></i> <span class="nav-label">资产管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ asset_list_active }}"><a href="{% url    'asset:asset_list' %}">资产信息</a></li>

                    <li class="{{ system_user_list_active }}"><a href="{% url    'asset:system_user' %}">系统用户</a></li>
                </ul>
            </li>


            <li class="{{ db_active }}">
                <a href="#"><i class="fa fa-drivers-license"></i> <span class="nav-label">数据库管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ db_list_active }}"><a href="{% url    'db:db_list' %}">数据库信息</a></li>

                    <li class="{{ db_user_active }}"><a href="{% url    'db:db_user_list' %}">数据库用户</a></li>
                </ul>
            </li>

           <li class="{{   release_active }}">
                <a href="#"><i class="fa fa-address-book-o"></i> <span class="nav-label">代码发布</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ release_list_active }}"><a href="{% url    'release:release_list' %}">代码库</a></li>

                </ul>
            </li>



            <li class="{{ tasks_active }}">
                <a href="#"><i class="fa fa-address-book-o"></i> <span class="nav-label">执行任务</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ cmd_active }}"><a href="{% url    'tasks:cmd' %}">命令行</a></li>
                    <li class="{{ tools_active }}"><a href="{% url    'tasks:tools' %}">工具</a></li>
                    <li class="{{ sql_active }}"><a href="{% url    'tasks:Inception' %}">数据库操作</a></li>
                </ul>
            </li>


            <li class="{{ library_active }}">
                <a href="#"><i class="fa fa-y-combinator-square"></i> <span class="nav-label">技术文档</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li class="{{ library_list_active }}"><a href="{% url    'library:library_list' %}">文档列表</a></li>
                </ul>
            </li>


            <li class="{{ autoops_active }}">
                <a href="#"><i class="fa fa-align-center"></i> <span class="nav-label">平台管理</span>
                    <span class="fa arrow"> </span></a>
                <ul class="nav nav-second-level">
                    <li><a href="/admin">xadmin后台</a></li>
                    <li><a href="/dadmin">django自带后台</a></li>
                    <li class="{{ login_log_active }}"><a href="{% url    'names:login_history' %}">历史记录</a></li>
                </ul>
            </li>

        </ul>

    </div>
</nav>

autoops/templates/_navbar-static-top.html
<div class="row border-bottom">
            <nav class="navbar navbar-static-top" role="navigation" style="margin-bottom: 0">
                <div class="navbar-header">
                    <a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>
{#                    <form role="search" class="navbar-form-custom" method="post" action="#">#}
{#                        <div class="form-group">#}
{#                            <input type="text" placeholder="请输入搜索内容" class="form-control" name="top-search" id="top-search">#}
{#                        </div>#}
{#                    </form>#}
                </div>
                <ul class="nav navbar-top-links navbar-right">
                    欢迎 {{ user  }} 使用 AutoOps  &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                    <li>
                        <a href="/logout.html">
                            <i class="fa fa-sign-out"></i> 注销
                        </a>
                    </li>
                </ul>

            </nav>
        </div>

autoops/templates/base.html
{% load  mytags %}
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>{% block  title %}{% endblock %}</title>

    {% include  "_css.html" %}
    {% block header-css %}
    {% endblock %}
</head>

<body>

<div id="wrapper"   class="container1">

    {% include "_nav.html" %}

    <div id="page-wrapper" class="gray-bg">
        {% include  "_navbar-static-top.html" %}

        {% block page-content %}


        {% endblock %}
        {% include  "_footer.html" %}

    </div>
</div>




<div class="container1">
    <div id="terminal"> </div>
</div>


{% include  "_js.html" %}
{% block footer-js %}
{% endblock %}





</body>

</html>

autoops/templates/index.html
{% extends "base.html" %}
{% block  title %}AutOps | 首页{% endblock %}



{% block header-css %}

{% for jsfile_name in script_list %}
        <script src="/static/echarts/{{ jsfile_name }}.js"></script>


{% endfor %}
{% endblock %}









{% block page-content %}

<div class="wrapper wrapper-content animated fadeInRight chart">
    <div class="row">
     <div class="col-sm-6">
        <div class="ibox float-e-margins">

            <div class="ibox-title">
                <h5>产品线</h5>
                <div class="ibox-tools">
                    <a class="collapse-links">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                            <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                                <i class="fa fa-wrench"></i>
                            </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">配置选项 1</a>
                        </li>
                        <li><a href="#">配置选项 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>

            </div>

            <div class="ibox-content  col-sm-12">
            <div  >{{ myechart|safe }}</div>
            </div>


        </div>

    </div>
    <div class="col-sm-6">
        <div class="ibox float-e-margins">

            <div class="ibox-title">
                <h5>数据中心</h5>
                <div class="ibox-tools">
                    <a class="collapse-links">
                        <i class="fa fa-chevron-up"></i>
                    </a>
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-wrench"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="#">配置选项 1</a>
                        </li>
                        <li><a href="#">配置选项 2</a>
                        </li>
                    </ul>
                    <a class="close-link">
                        <i class="fa fa-times"></i>
                    </a>
                </div>

            </div>

            <div class="ibox-content  col-sm-12" >
            <div  >{{ myechart1|safe }}</div>
            </div>


        </div>

    </div>

</div>
    </div>




{% endblock %}

{% block footer-js %}
    <script>

              toastr.options = {
                                      "closeButton": true,
                                      "debug": false,
                                      "progressBar": true,
                                      "preventDuplicates": true,
                                      "positionClass": "toast-top-right",
                                      "onclick": null,
                                      "showDuration": "400",
                                      "hideDuration": "1000",
                                      "timeOut": "7000",
                                      "extendedTimeOut": "1000",
                                      "showEasing": "swing",
                                      "hideEasing": "linear",
                                      "showMethod": "fadeIn",
                                      "hideMethod": "fadeOut"
                                    }
            ;



               toastr.success("欢迎来到AutoOps!", "欢迎")

</script>

    {{ onresize  | safe }}








{% endblock %}